### ISSUE TITLE
log時間輸出格式

### ISSUE THREAD

**Issue by lee850220** [makeding/aria2b#14]
目前觀察下來log所輸出的是UTC+0的時間，希望可以依照系統時區輸出。
第一次寫nodejs，寫了一段很醜的代碼：

**in common.js**
```javascript
function dt() {
    //return new Date().toJSON().replace('T', ' ').replace('Z', ' ').split('.')[0]
    return new Date().toLocaleDateString([],{year: "numeric",month: "2-digit",day: "2-digit"}).replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$1-$2") + " " + new Date().toLocaleTimeString([],{hourCycle: 'h23'})
}
```

**in app.js**
```javascript
process.env.TZ = '<your timezone>'
```

**Comment by makeding** [comment]
```
function dt() {
  const d = new Date()
  d.setMinutes(d.getMinutes() - d.getTimezoneOffset())
  return d.toJSON().replace('T', ' ').replace('Z', ' ').split('.')[0]
}
```

改了下，JS 的 `Date` 是可以直接获取到系统的时区的，当然我这就不改了，要不要尝试弄个 pull request 练手下 ？

**Comment by lee850220** [comment]
或是直接使用systemd輸出到journalctl，並把app.js裡所有的logt()改成log()。(因為journalctl已經有時間戳)

```properties
[Unit]
Description=aria2 ban unwelcome clients via ipset
After=network.target aria2.service

[Service]
Type=simple
User=root
Restart=on-failure
RestartSec=5s
ExecStart=/usr/bin/node /usr/local/bin/aria2b
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aria2b

[Install]
WantedBy=multi-user.target
```

在```vim /etc/rsyslog.conf```裡加入
```properties
:programname, isequal, "aria2b" -/var/log/aria2b.log
& stop
```

記得重啟rsyslog
```
systemctl restart rsyslog
```

範例輸出
![2022-04-01_031900](https://user-images.githubusercontent.com/18142489/161132854-be6b177d-370a-4414-b27d-80a50c2195dc.png)

**Comment by makeding** [comment]
目前想了下，这部分就以环境变量的形式安排比较好点？

日志前缀：
`Environment="OUTPREFIX=''"`  

不输出时间：
`Environment="OUTDATE=false"`

之类的来安排
// 取名困难，不知道这样好不好

**Comment by makeding** [comment]
> 以我的系統環境為例(UTC+8) 我嘗試使用原本的函數印出來的結果，看起來是直接印出格林威治時間(UTC+0) ![image](https://user-images.githubusercontent.com/18142489/161137196-f2346082-be7d-481c-a3c4-af55d516af80.png)

印象中我使用 .toJSON() 只是因为这个格式出来的直观点，然后 UTC 时间对于我来说没什么影响然后当时就懒得加时区回来了，修复后的代码可以参考[上面的 comments](https://github.com/makeding/aria2b/issues/14#issuecomment-1085006953) 

以及尝试下 fork 项目然后发个 pull request ？ 我觉得这样可以练练手熟悉下 Git(hub)

**Comment by makeding** [comment]
done [#b024962](https://github.com/makeding/aria2b/commit/b0249628b0524c531063cc08dab705b3cd0e8cdd)
