### ISSUE TITLE
在一种情况下不会自动ban IP

### ISSUE THREAD

**Issue by People-11** [makeding/aria2b#16]
如果aria2b开始运行时aria2内没有任务，则后续添加任务后，aria2b也不会自动ban迅雷IP，手动restart一下就好了

**Comment by People-11** [comment]
看了一下系统日志，aria2b正常启动，也输出了从aria2.conf获取配置的日志，然后就没有了，即使添加任务后连接状态里出现了迅雷的IP，也不会ban，日志里也没有显示任何东西

**Comment by makeding** [comment]
https://github.com/makeding/aria2b/issues/18
