### ISSUE TITLE
将aria2b集成到docker aria2中

### ISSUE THREAD

**Issue by SuperNG6** [makeding/aria2b#19]
刚发现这么好的一个项目，已将其集成到docker aria2中  
感谢作者，希望之后如果有更新，可以更新release，我这边会定期自动拉取并更新  
https://github.com/SuperNG6/docker-aria2

**Comment by SuperNG6** [comment]
另外再反馈一个bug，aria2b似乎无法正确读取时区, TZ=Asia/Shanghai  

![WiFrzW](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/WiFrzW.png)

**Comment by makeding** [comment]
时区的 bug 应该修了，直接使用 `toLocaleString` 安排了
然后 Release 是从 1.0.7 开始发布的，刚刚更新了 1.0.8 版本，同时增加了一个隐藏配置选项：
`HIDE_TIME_PREFIX=1`
即可隐藏时间
（此处配置选项为环境变量 需要加到 ENV 里面 ）

**Comment by SuperNG6** [comment]
> 时区的 bug 应该修了，直接使用 `toLocaleString` 安排了
> 然后 Release 是从 1.0.7 开始发布的，刚刚更新了 1.0.8 版本，同时增加了一个隐藏配置选项：
> `HIDE_TIME_PREFIX=1` （这里的1可以是任何字符串，按照你项目喜好可以是 =true）
> 即可隐藏时间
> （此处配置选项为环境变量 需要加到 ENV 里面 ）

好的，感谢，已集成
![S8teYR](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/S8teYR.png)
