### ISSUE TITLE
[功能请求] 封禁没有任何速度的IP

### ISSUE THREAD

**Issue by People-11** [makeding/aria2b#20]
![FireShot Capture 017 - AriaNg - 107 189 11 145](https://github.com/makeding/aria2b/assets/41558215/f56289aa-0dc4-4260-bbfd-1e50e35af8fb)
如图，里面有些IP，没有UA，没有进度，没有任何的上传和下载速度，但又占用着连接数，所以可不可以有一个选项，开启后封禁列表里长时间没有任何速度的IP

**Comment by People-11** [comment]
不过似乎没有意义，他们在一段时间后会自己断开

**Comment by makeding** [comment]
这种一般就是记录（钓鱼）用的 ip ，意义不明， ban 了意义感觉不大（还是被记录了）

如果想 ban 的话可以直接：

`XL,SD,XF,QD,BN,unknown`

就可以 ban 了

**Comment by People-11** [comment]
ao，谢谢

**Comment by People-11** [comment]
不过添加unknown之后并没有封禁没有标识的IP
![image](https://github.com/makeding/aria2b/assets/41558215/9034d947-c576-4e14-bd57-ef861fb8ac2c)

**Comment by makeding** [comment]
当时写代码的时候手滑了好像，不知道为什么首字母大写（
用 `Unknown`  看看

**Comment by People-11** [comment]
在Ban了，谢谢
